services: 
  sql:
    image: postgres:16
    container_name: sql
    ports:
      # external: internal (postgresi serveri sees)
      - 5432:5432
    volumes:
      - sql-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    logging:
      options: 
        max-size: 10m
        max-file: 3
        
  app:
    build: ./
    container_name: dogWalk-app
    ports:
      - 8080:8080
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: 3
    environment:
      ConnectionStrings__DefaultConnection: "Host=sql;Port=5432;Database=dogWalk;Username=postgres;Password=postgres"
    depends_on:
      - sql

volumes:
  sql-volume:
      